#+TITLE:   Emacs Java Imports
#+AUTHOR:  Lee Hinman
#+EMAIL:   leehinman@fastmail.com
#+LANGUAGE: en
#+PROPERTY: header-args :results code replace :exports both :noweb yes :tangle no
#+HTML_HEAD: <link rel="stylesheet" href="http://dakrone.github.io/org.css" type="text/css" />
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS: H:4 num:nil toc:t \n:nil @:t ::t |:t ^:{} -:t f:t *:t
#+OPTIONS: skip:nil d:(HIDE) tags:not-in-toc
#+TODO: TODO(t) | DONE(d)
#+TODO: TODO(t) SOMEDAY(s) INPROGRESS(i) HOLD(h) WAITING(w@/!) NEEDSREVIEW(n@/!) | DONE(d)
#+TODO: TODO(t) INPROGRESS(i) | CANCELLED(c@/!)
#+TAGS: export(e) noexport(n)
#+STARTUP: fold nodlcheck lognotestate showall

* Introduction

I needed a way to import java classes easily in Emacs.

This adds the =import-java-class= function, which will prompt for the class at
point, then the package, then add the required import statement for the class
and cache a "class-name -> package" relationship for any future importing of the
class.

It does this because I didn't want to drop into Intellij to add all the import
statements for my Java code, I just want to hit a key and have an import
statement added for the class under the point.

* Installation

=java-imports= is ([[https://github.com/milkypostman/melpa/pull/3333][not yet]]) available in the MELPA repository. Once it is:

Do this, if MELPA isn't already in your sources:

#+BEGIN_SRC emacs-lisp
(require 'package)
(add-to-list 'package-archives
             '("MELPA" . "https://melpa.org/packages/" ))
#+END_SRC

Then run =M-x package-refresh-contents= to load the contents of the new
repository, and =M-x package-install RET java-imports RET= to install
=java-imports=.

* Usage

#+BEGIN_SRC emacs-lisp
(require 'java-imports)
(define-key java-mode-map (kbd "M-I") 'java-imports-add-import)
#+END_SRC

* Things to do:

- [X] Avoid importing packages that already have import statements
- [ ] Inner classes?
- [ ] Add tests
